# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import reflection as _reflection
_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x65mbedding.proto\x12\tembedding\"\x1c\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"!\n\rEmbedResponse\x12\x10\n\x06vector\x18\x01 \x03(\x02\x42\x02\x10\x01\"\"\n\x11\x45mbedBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\">\n\x12\x45mbedBatchResponse\x12(\n\x07vectors\x18\x01 \x03(\x0b\x32\x18.embedding.EmbedResponse\"\x0f\n\rHealthRequest\"G\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x10\n\x0bvector_size\x18\x03 \x01(\x05\x32\xc5\x01\n\x10\x45mbeddingService\x12\x38\n\x05\x45mbed\x12\x17.embedding.EmbedRequest\x1a\x18.embedding.EmbedResponse\x12\x45\n\nEmbedBatch\x12\x1c.embedding.EmbedBatchRequest\x1a\x1d.embedding.EmbedBatchResponse\x12\x30\n\x06Health\x12\x18.embedding.HealthRequest\x1a\x18.embedding.HealthResponseB0Z.github.com/dremotha/mapbot/api/proto/embeddingb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'Z.github.com/dremotha/mapbot/api/proto/embedding'
    _EMBEDRESPONSE.fields_by_name['vector']._options = None
    _EMBEDRESPONSE.fields_by_name['vector']._serialized_options = b'\020\001'
    _EMBEDREQUEST._serialized_start = 30
    _EMBEDREQUEST._serialized_end = 58
    _EMBEDRESPONSE._serialized_start = 60
    _EMBEDRESPONSE._serialized_end = 93
    _EMBEDBATCHREQUEST._serialized_start = 95
    _EMBEDBATCHREQUEST._serialized_end = 129
    _EMBEDBATCHRESPONSE._serialized_start = 131
    _EMBEDBATCHRESPONSE._serialized_end = 193
    _HEALTHREQUEST._serialized_start = 195
    _HEALTHREQUEST._serialized_end = 210
    _HEALTHRESPONSE._serialized_start = 212
    _HEALTHRESPONSE._serialized_end = 283
    _EMBEDDINGSERVICE._serialized_start = 286
    _EMBEDDINGSERVICE._serialized_end = 483




